import { ProbabilityBarChart, ComparisonChart, ConfidenceBar } from "./Charts";

function EmptyState() {
  return (
    <div style={styles.emptyState}>
      <div style={styles.emptyOrbit}>
        <div style={styles.emptyRing1} />
        <div style={styles.emptyRing2} />
        <div style={styles.emptyPlanet}>
          <div style={styles.emptyPlanetInner} />
        </div>
      </div>
      <h3 style={styles.emptyTitle}>Awaiting Analysis</h3>
      <p style={styles.emptyDesc}>
        Enter stellar and orbital parameters in the left panel,
        then run the prediction to generate habitability analysis.
      </p>
      <div style={styles.emptyHints}>
        {["23 Input Parameters", "AI Classification", "Confidence Score"].map((h) => (
          <div key={h} style={styles.hintChip}>{h}</div>
        ))}
      </div>
    </div>
  );
}

function LoadingState() {
  return (
    <div style={styles.emptyState}>
      <div style={styles.loadOrbit}>
        <div style={styles.loadRing} />
        <div style={styles.loadCore} />
      </div>
      <h3 style={styles.loadTitle}>Analyzing Parameters</h3>
      <p style={styles.emptyDesc}>Running AI prediction model...</p>
      <div style={styles.loadDots}>
        {[0, 1, 2].map(i => (
          <div key={i} style={{ ...styles.loadDot, animationDelay: `${i * 0.2}s` }} />
        ))}
      </div>
    </div>
  );
}

function ResultCard({ icon, label, value, unit, color, glow }) {
  return (
    <div style={{ ...styles.resultCard, borderColor: `${color}22`, boxShadow: `0 0 30px ${glow || color}18` }}>
      <div style={{ ...styles.resultIcon, color, background: `${color}12`, borderColor: `${color}25` }}>
        {icon}
      </div>
      <div style={styles.resultContent}>
        <p style={styles.resultLabel}>{label}</p>
        <p style={{ ...styles.resultValue, color }}>
          {value}
          {unit && <span style={styles.resultUnit}> {unit}</span>}
        </p>
      </div>
    </div>
  );
}

export default function PredictionResult({ result, loading }) {
  if (loading) return <LoadingState />;
  if (!result) return <EmptyState />;

  const { predicted_planet_radius, habitability_class, habitability_probability } = result;
  const isHabitable = habitability_class === "Habitable";
  const habColor = isHabitable ? "#00ff80" : "#ff4a6e";
  const pct = Math.round(habitability_probability * 100);

  return (
    <div style={styles.resultRoot}>
      {/* Summary Banner */}
      <div style={{
        ...styles.banner,
        background: isHabitable ? "rgba(0,255,128,0.06)" : "rgba(255,74,110,0.06)",
        borderColor: isHabitable ? "rgba(0,255,128,0.2)" : "rgba(255,74,110,0.2)",
      }}>
        <div style={styles.bannerLeft}>
          <span style={{ ...styles.bannerIcon, fontSize: "2rem" }}>
            {isHabitable ? "🌍" : "☄️"}
          </span>
          <div>
            <p style={styles.bannerLabel}>Classification Result</p>
            <p style={{ ...styles.bannerClass, color: habColor }}>
              {habitability_class}
            </p>
          </div>
        </div>
        <div style={styles.bannerRight}>
          <p style={styles.bannerLabel}>Confidence</p>
          <p style={{ ...styles.bannerPct, color: habColor }}>{pct}%</p>
        </div>
      </div>

      {/* Metric Cards */}
      <div style={styles.cards}>
        <ResultCard
          icon="⬤"
          label="Predicted Planet Radius"
          value={predicted_planet_radius.toFixed(4)}
          unit="R⊕"
          color="#4ab8ff"
          glow="#0099ff"
        />
        <ResultCard
          icon="◈"
          label="Habitability Class"
          value={habitability_class}
          color={habColor}
          glow={habColor}
        />
        <ResultCard
          icon="◉"
          label="Habitability Probability"
          value={`${(habitability_probability * 100).toFixed(1)}%`}
          color="#a78bff"
          glow="#7c3aed"
        />
      </div>

      {/* Divider */}
      <div style={styles.divider}>
        <div style={styles.dividerLine} />
        <span style={styles.dividerLabel}>Visualizations</span>
        <div style={styles.dividerLine} />
      </div>

      {/* Charts */}
      <ConfidenceBar probability={habitability_probability} habitabilityClass={habitability_class} />
      <ProbabilityBarChart probability={habitability_probability} habitabilityClass={habitability_class} />
      <ComparisonChart predictedRadius={predicted_planet_radius} />

      {/* Footer note */}
      <p style={styles.footerNote}>
        ✦ Predictions generated by the AI model trained on NASA Kepler KOI dataset.
        Reference dataset average radius: 2.26 R⊕
      </p>

      <style>{resultCSS}</style>
    </div>
  );
}

const resultCSS = `
  @keyframes orbitFloat {
    0%, 100% { transform: rotate(0deg) translateX(38px) rotate(0deg); }
    100% { transform: rotate(360deg) translateX(38px) rotate(-360deg); }
  }
  @keyframes orbitFloat2 {
    0%, 100% { transform: rotate(0deg) translateX(60px) rotate(0deg); }
    100% { transform: rotate(-360deg) translateX(60px) rotate(360deg); }
  }
  @keyframes pulseCore {
    0%, 100% { transform: scale(1); opacity: 0.8; }
    50% { transform: scale(1.08); opacity: 1; }
  }
  @keyframes loadSpin {
    to { transform: rotate(360deg); }
  }
  @keyframes dotBounce {
    0%, 80%, 100% { transform: scale(0.8); opacity: 0.4; }
    40% { transform: scale(1.2); opacity: 1; }
  }
  @keyframes resultFadeIn {
    from { opacity: 0; transform: translateY(12px); }
    to { opacity: 1; transform: translateY(0); }
  }
`;

const styles = {
  resultRoot: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    animation: "resultFadeIn 0.5s ease both",
  },

  // Empty state
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "4rem 2rem",
    gap: "1.5rem",
    textAlign: "center",
    minHeight: "500px",
  },
  emptyOrbit: {
    position: "relative",
    width: "120px",
    height: "120px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyRing1: {
    position: "absolute",
    width: "100px",
    height: "100px",
    borderRadius: "50%",
    border: "1px solid rgba(74,184,255,0.15)",
  },
  emptyRing2: {
    position: "absolute",
    width: "140px",
    height: "140px",
    borderRadius: "50%",
    border: "1px dashed rgba(74,184,255,0.07)",
  },
  emptyPlanet: {
    width: "44px",
    height: "44px",
    borderRadius: "50%",
    background: "radial-gradient(circle at 35% 30%, #1a4060, #0a1a2e)",
    border: "1px solid rgba(74,184,255,0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    animation: "pulseCore 3s ease-in-out infinite",
  },
  emptyPlanetInner: {
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    background: "rgba(74,184,255,0.15)",
  },
  emptyTitle: {
    fontFamily: "'Orbitron', monospace",
    fontSize: "1rem",
    fontWeight: 700,
    color: "#2a5a7a",
    letterSpacing: "0.08em",
  },
  emptyDesc: {
    fontSize: "0.82rem",
    color: "#2a4a60",
    lineHeight: 1.7,
    maxWidth: "300px",
  },
  emptyHints: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  hintChip: {
    background: "rgba(0,100,200,0.08)",
    border: "1px solid rgba(0,100,200,0.15)",
    borderRadius: "20px",
    padding: "4px 12px",
    fontSize: "0.7rem",
    color: "#2a5070",
    letterSpacing: "0.04em",
  },

  // Loading state
  loadOrbit: {
    position: "relative",
    width: "80px",
    height: "80px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  loadRing: {
    position: "absolute",
    width: "80px",
    height: "80px",
    border: "2px solid transparent",
    borderTopColor: "#4ab8ff",
    borderRightColor: "rgba(74,184,255,0.3)",
    borderRadius: "50%",
    animation: "loadSpin 1s linear infinite",
  },
  loadCore: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    background: "radial-gradient(circle at 35% 35%, #1a6090, #0a2030)",
    boxShadow: "0 0 20px rgba(74,184,255,0.3)",
    animation: "pulseCore 1.5s ease-in-out infinite",
  },
  loadTitle: {
    fontFamily: "'Orbitron', monospace",
    fontSize: "0.9rem",
    fontWeight: 700,
    color: "#4ab8ff",
    letterSpacing: "0.08em",
  },
  loadDots: {
    display: "flex",
    gap: "8px",
  },
  loadDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "#4ab8ff",
    animation: "dotBounce 1.2s ease-in-out infinite",
  },

  // Banner
  banner: {
    borderRadius: "14px",
    padding: "1.25rem 1.5rem",
    border: "1px solid",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bannerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  bannerIcon: {},
  bannerLabel: {
    fontSize: "0.7rem",
    color: "#3a7090",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    fontWeight: 600,
    marginBottom: "3px",
  },
  bannerClass: {
    fontFamily: "'Orbitron', monospace",
    fontSize: "1.2rem",
    fontWeight: 900,
    letterSpacing: "0.05em",
  },
  bannerRight: { textAlign: "right" },
  bannerPct: {
    fontFamily: "'Orbitron', monospace",
    fontSize: "1.8rem",
    fontWeight: 900,
  },

  // Metric cards
  cards: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  resultCard: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    background: "rgba(0,15,35,0.5)",
    border: "1px solid",
    borderRadius: "12px",
    padding: "1rem 1.25rem",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  resultIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    border: "1px solid",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    flexShrink: 0,
  },
  resultContent: { flex: 1 },
  resultLabel: {
    fontSize: "0.7rem",
    color: "#3a7090",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontWeight: 600,
    marginBottom: "3px",
  },
  resultValue: {
    fontFamily: "'Orbitron', monospace",
    fontSize: "1rem",
    fontWeight: 700,
    letterSpacing: "0.03em",
  },
  resultUnit: {
    fontSize: "0.7rem",
    opacity: 0.7,
    fontWeight: 400,
  },

  // Divider
  divider: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    margin: "0.5rem 0",
  },
  dividerLine: {
    flex: 1,
    height: "1px",
    background: "rgba(255,255,255,0.06)",
  },
  dividerLabel: {
    fontSize: "0.65rem",
    color: "#2a5070",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },

  // Footer
  footerNote: {
    fontSize: "0.68rem",
    color: "#2a4a60",
    textAlign: "center",
    lineHeight: 1.6,
    borderTop: "1px solid rgba(255,255,255,0.04)",
    paddingTop: "1rem",
    marginTop: "0.5rem",
  },
};
